// Auto-generated index file - DO NOT EDIT MANUALLY
// This file is generated by generate-ts.sh
// Generated on: Sat, Jul 19, 2025  4:27:01 PM

// Individual file exports
export * from './gen/Protos/Nebula/Services/Fragments/Authentication/Claims_connect';
export * from './gen/Protos/Nebula/Services/Fragments/Authentication/Claims_pb';
export * from './gen/Protos/Nebula/Services/Fragments/Authentication/UserInterface_connect';
export * from './gen/Protos/Nebula/Services/Fragments/Authentication/UserInterface_pb';
export * from './gen/Protos/Nebula/Services/Fragments/Authentication/UserRecord_pb';
export * from './gen/Protos/Nebula/Services/Fragments/Organizations/EmployeeRecord_pb';
export * from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationInterface_connect';
export * from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationInterface_pb';
export * from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationInviteRecord_pb';
export * from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationRecord_pb';
export * from './gen/Protos/Nebula/Services/Fragments/Shared/OrganizationRoleAssignment_pb';

// Module namespace exports

// Organizations Module Namespace
export * as Organizations_EmployeeRecord from './gen/Protos/Nebula/Services/Fragments/Organizations/EmployeeRecord_pb';
export * as Organizations_OrganizationInterfaceConnect from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationInterface_connect';
export * as Organizations_OrganizationInterface from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationInterface_pb';
export * as Organizations_OrganizationInviteRecord from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationInviteRecord_pb';
export * as Organizations_OrganizationRecord from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationRecord_pb';

// Authentication Module Namespace
export * as Authentication_ClaimsConnect from './gen/Protos/Nebula/Services/Fragments/Authentication/Claims_connect';
export * as Authentication_Claims from './gen/Protos/Nebula/Services/Fragments/Authentication/Claims_pb';
export * as Authentication_UserInterfaceConnect from './gen/Protos/Nebula/Services/Fragments/Authentication/UserInterface_connect';
export * as Authentication_UserInterface from './gen/Protos/Nebula/Services/Fragments/Authentication/UserInterface_pb';
export * as Authentication_UserRecord from './gen/Protos/Nebula/Services/Fragments/Authentication/UserRecord_pb';

// Shared Module Namespace
export * as Shared_OrganizationRoleAssignment from './gen/Protos/Nebula/Services/Fragments/Shared/OrganizationRoleAssignment_pb';

// Convenience category exports

// gRPC Connect Services
export * as ClaimsService from './gen/Protos/Nebula/Services/Fragments/Authentication/Claims_connect';
export * as UserInterfaceService from './gen/Protos/Nebula/Services/Fragments/Authentication/UserInterface_connect';
export * as OrganizationInterfaceService from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationInterface_connect';

// Protobuf Messages
export * as ClaimsMessages from './gen/Protos/Nebula/Services/Fragments/Authentication/Claims_pb';
export * as UserInterfaceMessages from './gen/Protos/Nebula/Services/Fragments/Authentication/UserInterface_pb';
export * as UserRecordMessages from './gen/Protos/Nebula/Services/Fragments/Authentication/UserRecord_pb';
export * as EmployeeRecordMessages from './gen/Protos/Nebula/Services/Fragments/Organizations/EmployeeRecord_pb';
export * as OrganizationInterfaceMessages from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationInterface_pb';
export * as OrganizationInviteRecordMessages from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationInviteRecord_pb';
export * as OrganizationRecordMessages from './gen/Protos/Nebula/Services/Fragments/Organizations/OrganizationRecord_pb';
export * as OrganizationRoleAssignmentMessages from './gen/Protos/Nebula/Services/Fragments/Shared/OrganizationRoleAssignment_pb';

// End of auto-generated exports
